[package]
name = "small-fixed-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", optional = true }
typesize = { version = "0.1.3", optional = true }

[features]
typesize = ["dep:typesize"]
serde = ["dep:serde"]
