[package]
name = "small-fixed-array"
description = "A crate providing fixed length immutable collections with a low memory footprint."
repository = "https://github.com/GnomedDev/small-fixed-array"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
log = { version = "0.4.20", optional = true }
serde = { version = "1.0.193", optional = true }
tracing = { version = "0.1.40", optional = true }
typesize = { version = "0.1.3", optional = true }

[features]
typesize = ["dep:typesize"]
serde = ["dep:serde"]
log_using_tracing = ["dep:tracing"]
log_using_log = ["dep:log"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
