name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo test
        run: cargo +nightly test --all-features

  test-msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable 1.70 toolchain
        uses: dtolnay/rust-toolchain@1.70

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo test
        run: cargo test --features serde,typesize

  clippy-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo clippy on all feature combinations but nightly
        run: cargo hack --feature-powerset --exclude-features nightly clippy -- --deny warnings

  clippy-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo clippy on all feature combinations
        run: cargo +nightly hack clippy --feature-powerset -- --deny warnings
